_target_: solvers.claude_solver.ClaudeSolver
name: claude3_haiku
model: claude-3-haiku-20240307
api_key: "***" # replace with your Anthropic API key
image_root: "${basic.image_root}"
debug_mode: "${basic.debug_mode}"